export const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU';
export const SNACKBAR = 'SNACKBAR';
export const LOGIN = 'LOGIN';
export const REAL_TIME_TRAFFIC = 'REAL_TIME_TRAFFIC';
export const MAINPAGE_MOVETO_SECTION = 'MAINPAGE_MOVETO_SECTION';
export const HIDE_HEADER = 'HIDE_HEADER'