export const FETCH_MERCHANT_POS_LOGIN = 'FETCH_MERCHANT_POS_LOGIN';
export const FETCH_MERCHANT_PROFILE = 'FETCH_MERCHANT_PROFILE';
export const FETCH_MERCHANT_EMPLOYEE_LIST = 'FETCH_MERCHANT_EMPLOYEE_LIST';
export const CREATE_MERCHANT_EMPLOYEE = 'CREATE_MERCHANT_EMPLOYEE';