export const FETCH_MERCHANT_POS_LOGIN = 'FETCH_MERCHANT_POS_LOGIN';
export const FETCH_MERCHANT_PROFILE = 'FETCH_MERCHANT_PROFILE';
export const FETCH_MERCHANT_EMPLOYEE_LIST = 'FETCH_MERCHANT_EMPLOYEE_LIST';
export const CREATE_MERCHANT_EMPLOYEE = 'CREATE_MERCHANT_EMPLOYEE';
export const DELETE_MERCHANT_EMPLOYEE = 'DELETE_MERCHANT_EMPLOYEE';
export const OPEN_EDIT_MERCHANT_EMPLOYEE = 'OPEN_EDIT_MERCHANT_EMPLOYEE';
export const CLOSE_EDIT_MERCHANT_EMPLOYEE = 'CLOSE_EDIT_MERCHANT_EMPLOYEE';
export const ASSIGN_MERCHANT_EMPLOYEE = 'ASSIGN_MERCHANT_EMPLOYEE';
