import React, { Component } from 'react';
import { Link } from 'react-router';
import { root_page } from '../utilities/urlPath'
import Footer from '../components/Footer';
import MuiThemeProvider from 'material-ui/styles/MuiThemeProvider';

class WebSiteTerm extends Component {

    constructor(props) {
        super(props);
        this.state = {
        }
    }

    render() {

        return (
            <MuiThemeProvider>
                <div>
                    <div className="doc-background">
                        <p className="txt-2" style={{ textAlign: 'center' }}>Web Site Term of Use</p>
                        <p className="txt-4">Welcome to <Link to={`${root_page}`}>www.opay.ca</Link>  (the "OPAY web site" or "Site"). The services on this Site are offered to you by OPAY Inc. ("OPAY") subject to the following terms (the "Terms"). If you access and use the OPAY web site you accept and agree to be bound by and comply with the Terms. If you do not accept the Terms you may not use the OPAY web site; please immediately log off this Site.</p>
                        <p className="txt-4">OPAY does not sell products for children. If you are under the age of 18 you may use the OPAY web site only with the involvement of a parent or guardian.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>Use of the OPAY Web Site</p>
                        <p className="txt-4">OPAY maintains this Site for your information, education and communication. You may not reproduce, distribute, modify, display or prepare derivative works based on or otherwise use the content of the Site without OPAY' prior written permission.</p>
                        <p className="txt-4">You may not use the Site for any purpose that is unlawful or prohibited by the Terms. You may not use the Site in any manner that could damage, disable, overburden or impair any OPAY server or the network connected to any OPAY server or interfere with any other party's use and enjoyment of the Site. You may not attempt to gain unauthorized access to OPAY information or services, other accounts, computer systems or networks or to any service provided by OPAY through hacking, password mining or any other means. You may not obtain or attempt to obtain any OPAY information or services through any means not intentionally made available through the Site.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>Communications to OPAY Inc.</p>
                        <p className="txt-4">When you visit the OPAY web site or send e-mail to us you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirements that such communications be in writing.</p>
                        <p className="txt-4">However, in your communications with OPAY please keep in mind that OPAY does not accept or consider any creative ideas or suggestions relating to products or marketing plans unless it has specifically requested them. The sole purpose of this policy is to avoid potential misunderstandings or disputes when OPAY’ products or marketing strategies might seem similar to ideas submitted to OPAY. If, despite our request that you not send us your ideas and materials, you still send them, please understand that OPAY makes no assurances that your ideas and materials will be treated as confidential or proprietary.</p>
                        <p className="txt-4">By posting, uploading, inputting, providing or submitting any materials you are granting OPAY and its sublicenses permission to use your materials in connection with the operation of their Internet businesses including, without limitation, the license rights to copy, distribute, transmit, publicly display, publicly perform, reproduce, edit, translate and re-format your materials; to publish your name in connection with your materials; and the right to sublicense such rights. No compensation will be paid with respect to the use of your materials</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>Notice Specific to Software Available on this Site</p>
                        <p className="txt-4">Any software that is made available to download ("Software") is the copyrighted work of OPAY and/or its suppliers. Use of the Software is governed by the terms of the end user license agreement, if any, which accompanies or is included with the Software ("License Agreement"). An end user will be unable to install any Software that is accompanied by or includes a License Agreement until he or she first agrees to the License Agreement terms.</p>
                        <p className="txt-4">The Software is made available for download solely for use by end users according to the License Agreement. Any reproduction or re-distribution of the Software not in accordance with the License Agreement is expressly prohibited by law.</p>
                        <p className="txt-4">The Software is warranted, if at all, only according to the terms of the License Agreement. Except as warranted in the License Agreement, OPAY hereby disclaims all warranties and conditions with regard to the Software, including all warranties and conditions of merchantability, whether express, implied or statutory, fitness for a particular purpose, title and non-infringement.</p>
                        <p className="txt-4">For your convenience, OPAY may make available tools and utilities for use and/or download. OPAY does not make any assurances with regard to the accuracy of the results or output that derive from the use of any such tools and utilities. Please respect the intellectual property rights of others when using the tools and utilities made available.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>No Warranties</p>
                        <p className="txt-4">OPAY provides the web site and the information, material and content (collectively, the "Information") on an "as is, where is" basis and does not make any express or implied warranties, representations, endorsements or conditions with respect to the OPAY web site or the Information, including, without limitation, warranties as to merchantability, operation, non-infringement, usefulness, completeness, accuracy, currency, reliability and fitness for a particular purpose. Further, OPAY does not represent or warrant that the web site will be available and meet your requirements, that access will be uninterrupted, that there will be no delays, failures, errors or omissions or loss of transmitted information, that no viruses or other contaminating or destructive properties will be transmitted or that no damage will occur to your computer system. You have sole responsibility for adequate protection and backup of data and/or equipment and to take reasonable and appropriate precautions to scan for computer viruses or other destructive properties. OPAY shall not be liable for any direct, indirect, incidental, consequential, special, exemplary or punitive damages arising out of your use of or inability to use the OPAY web site or the Information or any action or decision made by you in reliance on the OPAY web site or the Information or any unauthorized use or reproduction of the OPAY web site or the Information even if OPAY has been advised of the possibility of these damages.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>General</p>
                        <p className="txt-4">The information, material and content provided in the OPAY web site may be changed at any time without notice. Changes may be made to the Terms at any time without notice by updating this posting. You agree to review the Terms regularly and your continued access or use of the OPAY web site will mean that you agree to any changes. OPAY controls and operates this Site from its headquarters in Markham, Ontario, Canada and makes no representation that the Site is appropriate or available for use in other locations. If you use this Site from other locations you are responsible for compliance with applicable local laws. If any portion of these Terms is held to be unenforceable, the unenforceable portion shall be construed in accordance with applicable law to the greatest extent possible and the balance of the provisions shall remain in full force and effect. Any cause of action you may have with respect to this Site must be commenced within one (1) year after the claim or cause of action arises or such claim or cause of action is barred. These Terms will be governed by and construed in accordance with the laws of the Province of Ontario and the laws of Canada applicable therein, without giving effect to any principles of conflicts of laws. All disputes, controversies or claims arising out of or in connection with the Site shall be submitted to and be subject to the jurisdiction of the courts of the Province of Ontario. You submit and attorn to the exclusive jurisdiction of the courts of the Province of Ontario to finally adjudicate or determine any suit, action or proceeding arising out of or in connection with the OPAY web site.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>Copyrights</p>
                        <p className="txt-4">You should assume that everything you see or read on the OPAY web site is copyrighted unless otherwise noted and may not be used except as provided in these Terms or in the text on the OPAY web site without the written permission of OPAY. OPAY neither warrants nor represents that your use of materials displayed on the OPAY web site will not infringe rights of third parties not owned by or affiliated with OPAY. Images, photographs or illustrations displayed on the web site are either the property of, or used with permission by, OPAY. The use of these materials by you or anyone else authorized by you, is prohibited unless specifically permitted by these Terms or specific permission provided elsewhere on the OPAY web site. Any unauthorized use of the images may violate copyright laws, trade mark laws, the laws of privacy and publicity and communications regulations and statutes.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>Trade Marks</p>
                        <p className="txt-4">The trade marks, logos and service marks (collectively, the "Trade Marks") displayed on the OPAY web site are registered and unregistered trademarks of OPAY. Nothing contained on the OPAY web site should be construed as granting, by implication, estoppel or otherwise any license or right to use any Trade Mark displayed on the OPAY web site without the written permission of OPAY or such third party that may own the Trade Mark displayed on the OPAY web site. Your misuse of the Trade Marks displayed on the OPAY web site or any other content on the OPAY web site except as provided herein, is strictly prohibited.</p>
                        <p className="txt-3" style={{ fontWeight: 'bold' }}>Privacy and Protection of Personal Information</p>
                        <p className="txt-4">OPAY is concerned about the protection of on-line privacy for all visitors to the OPAY web site. Please see our full Privacy Policy relating to the collection and use of your information which also governs your visit to the OPAY web site, to understand our practices.</p>
                        <p className="txt-4">Please contact us to find out more.</p>
                        <br />
                    </div>
                    <Footer />
                </div>
            </MuiThemeProvider>
        );

    }
}

export default WebSiteTerm